Repository Orillusion/orillusion, pull requests merged in 2023-11, with the labels that each got.

#320 chore: chore graphic sample
  samples/graphic/Sample_GraphicMeshWave.ts
  samples/graphic/Sample_GraphicMesh_0.ts
  samples/graphic/Sample_GraphicMesh_1.ts
  samples/graphic/Sample_GraphicMesh_2.ts
  samples/graphic/Sample_GraphicMesh_3.ts
  samples/graphic/Sample_GraphicMesh_4.ts
  samples/graphic/Sample_GraphicMesh_5.ts
  samples/graphic/Sample_GraphicMesh_6.ts
  samples/graphic/Sample_GraphicMesh_7.ts
Labels: feature

#338 perf: use pixelRatio from UIPanel.
  samples/gui/Sample_UIPerformance2.ts
  src/Engine3D.ts
  src/components/gui/GUIConfig.ts
  src/components/gui/GUIPickHelper.ts
  src/components/gui/core/GUIMaterial.ts
  src/components/gui/core/GUIShader.ts
  src/components/gui/uiComponents/UIInteractive.ts
  src/components/gui/uiComponents/UIPanel.ts
Labels: bug, feature

#337 fix: Shadow of double side materials.
  src/materials/Material.ts
Labels: bug
