Repository Orillusion/orillusion, pull requests merged in 2023-05, with the labels that each got.

#91 test: add test sample
  .github/workflows/ci.yml
  src/components/ComponentBase.ts
  test/components/DirectionLight_lighting.test.ts
  test/components/ECS.test.ts
  test/components/GTAOPostEffects.test.ts
  test/components/GlobalFogEffects.test.ts
  test/components/HDRBloomPostEffects.test.ts
  test/components/PointLight_lighting.test.ts
  test/components/SSRPostEffects.test.ts
  test/components/SpotLight_lighting.test.ts
  test/components/TAAPostEffects.test.ts
  test/components/Texture.test.ts
  test/components/component.test.ts
  test/components/componentLife-Camera3D.test.ts
  test/components/lightingShadow.test.ts
  test/components/test/TestComponents.ts
  test/components/transform.test.ts
  test/gfx/ComputeGPUBuffer.test.ts
  test/gfx/GPUContext.test.ts
  test/gfx/StorageGPUBuffer.test.ts
  test/gfx/StructGPUBuffer.test.ts
  test/gfx/WebgpuContext.test.ts
  test/math/AnimationCurve.test.ts
  test/math/Bezier2DCurve.test.ts
  test/math/Color.test.ts
  test/math/HaltonSeq.test.ts
  test/math/Matrix3.test.ts
  test/math/Matrix4.test.ts
  test/math/MatrixDO.test.ts
  test/math/Plane.test.ts
  test/math/Quaternion.test.ts
  test/math/Rand.test.ts
  test/math/Ray.test.ts
  test/math/Rect.test.ts
  test/math/Triangle.test.ts
  test/math/UV.test.ts
  test/math/Vector2.test.ts
  test/math/Vector3.test.ts
  test/math/Vector4.test.ts
  test/shader/ComputeShader.test.ts
  test/shader/RenderShader.test.ts
  test/system/EventSystem.test.ts
  test/util.ts
Labels: feature

#94 fix(ci): use swiftshader(cpu based vulkan driver) as webgpu adaptor
  .github/workflows/ci.yml
  package.json
Labels: feature

#88 fix(matrix4): fix multiply function
  src/math/Matrix4.ts
Labels: bug

#90 feat(GUIHelp): add GUIHelp class
  packages/debug/GUIHelp.ts
  samples/base/Sample_Base_0.ts
Labels: feature

#93 chore: move property animation file
  src/Engine3D.ts
  src/components/ComponentBase.ts
  src/components/anim/curveAnim/AnimationMonitor.ts
  src/components/anim/curveAnim/AttributeAnimCurve.ts
  src/components/anim/curveAnim/PropertyAnimClip.ts
  src/components/anim/curveAnim/PropertyAnimation.ts
  src/components/anim/curveAnim/PropertyAnimationEvent.ts
  src/components/anim/curveAnim/PropertyHelp.ts
  src/core/View3D.ts
  src/gfx/renderJob/collect/ComponentCollect.ts
  src/gfx/renderJob/jobs/RendererJob.ts
  src/index.ts
  src/math/CubicBezierCurve.ts
  src/math/CubicBezierPath.ts
  tsconfig.json
Labels: feature

#98 feat(sample): Sample blend mode
  samples/render/Sample_BlendMode.ts
  samples/render/Sample_ChangeTexture.ts
Labels: feature

#96 feat(sample): add sky texture samples
  samples/sky/Sample_AtmosphericSky.ts
  samples/sky/Sample_BitmapCubeSky.ts
  samples/sky/Sample_BitmapCubeStdSky.ts
  samples/sky/Sample_HDRSky.ts
  samples/sky/Sample_LDRSky.ts
  samples/sky/Sample_SolidColorSky.ts
Labels: feature

#99 fix(AtmosphericComponent): fix AtmosphericComponent Update
  src/Engine3D.ts
  src/assets/shader/lighting/BxDF_frag.ts
  src/assets/shader/sky/AtmosphericScatteringSky_shader.ts
  src/components/AtmosphericComponent.ts
  src/components/renderer/MeshRenderer.ts
  src/core/entities/Entity.ts
  src/math/TimeInterpolator.ts
  src/textures/AtmosphericScatteringSky.ts
Labels: bug, feature

#102 fix(engine): engine shadow lights collect init bug
  src/Engine3D.ts
  src/gfx/renderJob/jobs/RendererJob.ts
Labels: bug

#100 fix: image&video material shader and skeleton animation event
  packages/media-extention/ImageMaterial.ts
  packages/media-extention/VideoMaterial.ts
  src/components/anim/skeletonAnim/SkeletonAnimationClipState.ts
Labels: bug

#101 feat(sample): add light sample
  samples/index.ts
  samples/lights/PointLightsScript.ts
  samples/lights/Sample_DirectLight.ts
  samples/lights/Sample_PointLight.ts
  samples/lights/Sample_PointLightShadow.ts
  samples/lights/Sample_SpotLight.ts
  src/components/ComponentBase.ts
  src/components/lights/LightBase.ts
Labels: feature

#97 feat(outline): add outlineManager
  src/gfx/renderJob/post/OutlinePost.ts
  src/io/OutlineManager.ts
  src/io/OutlinePostData.ts
Labels: feature

#104 feat(outline): add OutlineManager
  src/index.ts
  src/io/OutlineManager.ts
Labels: feature

#105 feat(sample): add samples about material
  samples/base/Sample_Transform.ts
  samples/index.ts
  samples/loader/Sample_FlightHelmet.ts
  samples/loader/Sample_LoadGLTF.ts
  samples/material/Sample_CustomMaterial.ts
  samples/material/Sample_PBR.ts
  samples/material/Sample_PBRMaterial.ts
  samples/material/Sample_RenderPassClean.ts
  samples/material/Sample_ReplaceMaterial.ts
  samples/material/Sample_UVMove.ts
  samples/material/Sample_UnlitMaterial.ts
  samples/material/script/UVMoveComponent.ts
  samples/render/Sample_BlendMode2.ts
  samples/render/Sample_CullMode.ts
  samples/render/Sample_TextureSample.ts
  samples/sky/Sample_AtmosphericSky.ts
  samples/utils/GUIUtil.ts
  test/components/test/TestComponents.ts
Labels: feature

#108 fix(MatrixDO): MatrixDO Buffer
  samples/base/Sample_Transform.ts
  samples/material/Sample_PBRMaterial.ts
  src/Engine3D.ts
  src/components/Transform.ts
  src/components/renderer/RenderNode.ts
  src/core/Scene3D.ts
  src/gfx/graphics/webGpu/core/bindGroups/GlobalUniformGroup.ts
  src/gfx/graphics/webGpu/core/bindGroups/MatrixBindGroup.ts
  src/math/Matrix4.ts
Labels: bug

#109 fix(ies): light ies has bug
  src/components/lights/LightBase.ts
  src/components/lights/LightData.ts
  src/gfx/graphics/webGpu/core/bindGroups/groups/LightEntries.ts
Labels: bug

#106 fix(HDRBloomPost): add luminosityThreshold arg
  src/Engine3D.ts
  src/gfx/renderJob/post/HDRBloomPost.ts
  src/setting/post/BloomSetting.ts
Labels: feature

#110 fix(sample): remove errors
  samples/base/Sample_InitEngine.ts
  samples/base/Sample_Transform.ts
  samples/base/Sample_UseComponent.ts
  samples/lights/Sample_DirectLight.ts
  samples/lights/Sample_PointLight.ts
  samples/lights/Sample_PointLightShadow.ts
  samples/lights/Sample_SpotLight.ts
  samples/loader/Sample_FlightHelmet.ts
  samples/loader/Sample_LoadGLTF.ts
  samples/material/Sample_CustomMaterial.ts
  samples/material/Sample_PBR.ts
  samples/material/Sample_PBRMaterial.ts
  samples/material/Sample_RenderPassClean.ts
  samples/material/Sample_ReplaceMaterial.ts
  samples/material/Sample_UVMove.ts
  samples/material/Sample_UnlitMaterial.ts
  samples/render/Sample_BlendMode.ts
  samples/render/Sample_BlendMode2.ts
  samples/render/Sample_ChangeTexture.ts
  samples/render/Sample_CullMode.ts
  samples/render/Sample_TextureSample.ts
  samples/sky/Sample_AtmosphericSky.ts
  samples/sky/Sample_BitmapCubeSky.ts
  samples/sky/Sample_BitmapCubeStdSky.ts
  samples/sky/Sample_HDRSky.ts
  samples/sky/Sample_LDRSky.ts
  samples/sky/Sample_SolidColorSky.ts
Labels: bug

#118 refactor(form): refactor form to from
  src/components/Transform.ts
  src/components/lights/IESProfiles.ts
  src/core/geometry/GeometryBase.ts
  src/core/geometry/GeometryIndicesBuffer.ts
  src/io/OutlinePostData.ts
  src/math/AnimationCurve.ts
  src/math/Bezier3D.ts
  src/math/Color.ts
  src/math/Matrix4.ts
  test/math/Color.test.ts
Labels: feature

#114 feat(sample): sample of loader
  samples/loader/Sample_FlightHelmet.ts
  samples/loader/Sample_LoadGLB.ts
  samples/loader/Sample_LoadGLTF.ts
  samples/loader/Sample_LoadJson.ts
  samples/material/Sample_PBRMaterial.ts
  samples/material/Sample_UVMove.ts
  samples/render/Sample_BlendMode2.ts
Labels: feature

#119 fix(videoTexture): force video refresh at rendering frameRate
  packages/media-extention/VideoTexture.ts
  packages/media-extention/package.json
  samples/material/Sample_VideoMaterial.ts
Labels: bug

#115 feat(sample): samples of animation
  samples/animation/Sample_CurveAnimation.ts
  samples/animation/Sample_MorphTarget.ts
  samples/animation/Sample_Skeleton.ts
  samples/animation/Sample_Skeleton2.ts
  samples/animation/Sample_Skeleton3.ts
  src/util/Object3DUtil.ts
Labels: feature

#126 docs: add contributing guide
  .github/CODE_OF_CONDUCT.md
  .github/commit-convention.md
  .github/contributing.md
  README.md
  vite.config.js
Labels: documentation

#131 fix(graphic): fix graphic draw bound
  samples/post/Sample_taa.ts
  src/Engine3D.ts
  src/assets/shader/core/struct/EmptyFrag_CommonFragment.ts
  src/assets/shader/core/struct/EmptyFrag_FragmentOutput.ts
  src/components/lights/PointLight.ts
  src/components/lights/SpotLight.ts
  src/core/View3D.ts
  src/core/bound/BoundingBox.ts
  src/core/bound/BoundingSphere.ts
  src/core/bound/Frustum.ts
  src/core/bound/IBound.ts
  src/core/entities/Entity.ts
  src/gfx/renderJob/jobs/RendererJob.ts
  src/gfx/renderJob/passRenderer/color/ColorPassRenderer.ts
  src/gfx/renderJob/passRenderer/graphic/Graphic3DBatchRenderer.ts
  src/gfx/renderJob/passRenderer/graphic/Graphic3DRender.ts
  src/index.ts
  src/math/Ray.ts
  src/shape/SphereGeometry.ts
  test/math/Ray.test.ts
Labels: bug

#116 feat(sample): sample of geometry
  samples/geometry/Sample_CustomGeometry.ts
  samples/geometry/Sample_InternalGeometry.ts
  samples/geometry/Sample_VertexAnimation.ts
  src/core/geometry/GeometryBase.ts
Labels: feature

#132 fix(sample): update shadowRameRate
  samples/animation/Sample_Skeleton.ts
  samples/animation/Sample_Skeleton2.ts
Labels: bug

#124 feat(sample): Add sample about pick
  samples/pick/MaterialStateComponent.ts
  samples/pick/Sample_BoxColliderPick.ts
  samples/pick/Sample_OutlineEffectPick.ts
  samples/pick/Sample_PixelPick.ts
  samples/utils/ExampleScene.ts
Labels: feature

#137 fix(light): remove light
  samples/animation/Sample_Skeleton3.ts
  src/Engine3D.ts
  src/assets/shader/cluster/ClusterBoundsSource_cs.ts
  src/assets/shader/cluster/ClusterLighting_cs.ts
  src/assets/shader/sky/CubeSky_Shader.ts
  src/components/renderer/MeshRenderer.ts
  src/core/bound/Frustum.ts
  src/core/entities/Entity.ts
  src/core/geometry/GeometryBase.ts
  src/gfx/graphics/webGpu/core/bindGroups/GlobalUniformGroup.ts
  src/gfx/graphics/webGpu/core/bindGroups/groups/LightEntries.ts
  src/gfx/graphics/webGpu/core/buffer/GPUBufferBase.ts
  src/gfx/renderJob/jobs/RendererJob.ts
  src/gfx/renderJob/passRenderer/RendererBase.ts
  src/gfx/renderJob/passRenderer/cluster/ClusterLightingBuffer.ts
  src/gfx/renderJob/passRenderer/cluster/ClusterLightingRender.ts
  src/gfx/renderJob/passRenderer/color/ColorPassRenderer.ts
  src/gfx/renderJob/passRenderer/preDepth/PreDepthPassRenderer.ts
  src/gfx/renderJob/passRenderer/shadow/PointLightShadowRenderer.ts
  src/gfx/renderJob/passRenderer/shadow/ShadowMapPassRenderer.ts
Labels: bug

#142 fix(destroy): destroy has bug
  samples/base/Sample_AddRemove.ts
  samples/lights/Sample_PointLight.ts
  src/components/Transform.ts
  src/components/renderer/MeshRenderer.ts
  src/components/renderer/RenderNode.ts
  src/core/bound/BoundingBox.ts
  src/core/entities/Entity.ts
  src/core/geometry/GeometryBase.ts
  src/core/geometry/GeometryIndicesBuffer.ts
  src/core/geometry/GeometryVertexBuffer.ts
  src/core/pool/memory/MemoryInfo.ts
  src/gfx/graphics/webGpu/core/buffer/GPUBufferBase.ts
  src/gfx/graphics/webGpu/shader/ComputeShader.ts
  src/gfx/graphics/webGpu/shader/ShaderBase.ts
  src/gfx/renderJob/passRenderer/cluster/ClusterLightingRender.ts
  src/materials/LitMaterial.ts
  src/materials/MaterialPass.ts
  src/materials/PhysicMaterial.ts
Labels: bug

#139 feat(sample): add sample about physics
  samples/physics/Sample_Physics01.ts
  samples/physics/Sample_PhysicsBox.ts
Labels: feature

#143 fix(renderOpt): fix poor performance in handling shadow
  .github/contributing.md
  packages/debug/GUIHelp.ts
  packages/debug/dat.gui.d.ts
  packages/debug/dat.gui.module.d.ts
  packages/debug/dat.gui.module.js
  samples/animation/Sample_Skeleton.ts
  samples/animation/Sample_Skeleton2.ts
  samples/animation/Sample_Skeleton3.ts
  samples/base/Sample_AddRemove.ts
  samples/lights/Sample_AddRemovePointLight.ts
  samples/lights/Sample_DirectLightShadow.ts
  samples/post/Sample_taa.ts
  src/Engine3D.ts
  src/assets/shader/cluster/ClusterBoundsSource_cs.ts
  src/assets/shader/materials/program/ShadowMapping_frag.ts
  src/components/lights/LightBase.ts
  src/components/renderer/RenderNode.ts
  src/core/View3D.ts
  src/gfx/graphics/webGpu/core/bindGroups/groups/LightEntries.ts
  src/gfx/graphics/webGpu/core/buffer/GPUBufferBase.ts
  src/gfx/renderJob/collect/EntityCollect.ts
  src/gfx/renderJob/collect/ShadowLightsCollect.ts
  src/gfx/renderJob/frame/ProbeGBufferFrame.ts
  src/gfx/renderJob/jobs/RendererJob.ts
  src/gfx/renderJob/passRenderer/cluster/ClusterLightingRender.ts
  src/materials/LitMaterial.ts
  vite.config.js
Labels: bug

#133 fix(geometry): fix error multi geometry
  samples/geometry/Sample_InternalGeometry.ts
  src/components/renderer/RenderNode.ts
  src/shape/PlaneGeometry.ts
Labels: bug

#147 fix(shadow): fix shadow cullmode
  src/gfx/generate/PassGenerate.ts
Labels: bug

#146 feat(sample): add property animation sample
  samples/animation/Sample_PropertyAnimation.ts
  src/components/anim/curveAnim/PropertyAnimClip.ts
Labels: feature

#161 fix(ComponentCollect): break component dependency for engine3D
  src/Engine3D.ts
  src/components/Transform.ts
  src/core/entities/Object3D.ts
  src/gfx/renderJob/collect/ComponentCollect.ts
  src/gfx/renderJob/collect/ShadowLightsCollect.ts
Labels: bug

#160 chore(reference): about destroy
  samples/base/Sample_Destroy.ts
  src/Engine3D.ts
  src/components/Transform.ts
  src/components/renderer/MeshRenderer.ts
  src/components/renderer/RenderNode.ts
  src/gfx/graphics/webGpu/core/texture/Texture.ts
  src/gfx/graphics/webGpu/shader/ComputeShader.ts
  src/gfx/graphics/webGpu/shader/RenderShader.ts
  src/gfx/renderJob/passRenderer/RendererBase.ts
  src/gfx/renderJob/passRenderer/color/ColorPassRenderer.ts
  src/gfx/renderJob/post/PostBase.ts
  src/index.ts
  src/materials/MaterialPass.ts
  src/materials/PhysicMaterial.ts
  src/util/Reference.ts
Labels: bug, feature

#163 fix(canvas): refine canvas init
  src/gfx/graphics/webGpu/Context3D.ts
Labels: bug

#157 feat(GUI): add GUI feature
  samples/gui/Sample_UIButton.ts
  samples/gui/Sample_UIImageColor.ts
  samples/gui/Sample_UIMultiPanel.ts
  samples/gui/Sample_UIPanelOrder.ts
  samples/gui/Sample_UISingleImage.ts
  samples/gui/Sample_UISpriteSheet.ts
  samples/gui/Sample_UITextField.ts
  samples/gui/Sample_UIVideo.ts
  samples/gui/panel/GUIBinder.ts
  samples/gui/panel/GUIPanelPOI.ts
  src/assets/Fonts.ts
  src/assets/Res.ts
  src/components/BillboardComponent.ts
  src/components/ComponentBase.ts
  src/components/controller/HoverCameraController.ts
  src/components/gui/GUIConfig.ts
  src/components/gui/GUIExtension.ts
  src/components/gui/GUIPick.ts
  src/components/gui/GUIPickHelper.ts
  src/components/gui/core/GUIAtlasTexture.ts
  src/components/gui/core/GUICanvas.ts
  src/components/gui/core/GUIGeometry.ts
  src/components/gui/core/GUIGeometryRebuild.ts
  src/components/gui/core/GUIMaterial.ts
  src/components/gui/core/GUIMesh.ts
  src/components/gui/core/GUIQuad.ts
  src/components/gui/core/GUIRenderer.ts
  src/components/gui/core/GUIShader.ts
  src/components/gui/core/GUISprite.ts
  src/components/gui/core/GUITexture.ts
  src/components/gui/uiComponents/IUIInteractive.ts
  src/components/gui/uiComponents/TextFieldLayout.ts
  src/components/gui/uiComponents/UIButton.ts
  src/components/gui/uiComponents/UIComponentBase.ts
  src/components/gui/uiComponents/UIImage.ts
  src/components/gui/uiComponents/UIInteractive.ts
  src/components/gui/uiComponents/UIPanel.ts
  src/components/gui/uiComponents/UITextField.ts
  src/components/gui/uiComponents/UITransform.ts
  src/components/gui/uiComponents/ViewPanel.ts
  src/components/gui/uiComponents/WorldPanel.ts
  src/components/renderer/RenderNode.ts
  src/core/View3D.ts
  src/core/entities/Entity.ts
  src/gfx/renderJob/collect/EntityCollect.ts
  src/gfx/renderJob/occlusion/OcclusionSystem.ts
  src/index.ts
  src/loader/FileLoader.ts
  src/loader/parser/AtlasParser.ts
  src/loader/parser/FontParser.ts
  src/loader/parser/OBJParser.ts
  src/loader/parser/ParserBase.ts
  src/loader/parser/gltf/GLTFParser.ts
  src/util/ZSorterUtil.ts
Labels: feature

#171 fix(hdrSky): Distinguish HDR/LDR texture
  samples/sky/Sample_AtmosphericSky.ts
  samples/sky/Sample_BitmapCubeSky.ts
  samples/sky/Sample_BitmapCubeStdSky.ts
  samples/sky/Sample_HDRSky.ts
  samples/sky/Sample_LDRSky.ts
  samples/sky/Sample_SolidColorSky.ts
  samples/utils/ExampleScene.ts
  src/assets/shader/sky/CubeSky_Shader.ts
  src/gfx/graphics/webGpu/core/texture/Texture.ts
  src/index.ts
  src/materials/SkyMaterial.ts
  src/textures/AtmosphericScatteringSky.ts
  src/textures/HDRTexture.ts
  src/textures/HDRTextureCube.ts
  src/textures/LDRTextureCube.ts
  src/textures/SolidColorSky.ts
  src/textures/TextureCubeFaceData.ts
Labels: bug

#170 fix(android): reslove webgpu errors
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report_zh.md
  README.md
  src/gfx/graphics/webGpu/Context3D.ts
  src/gfx/graphics/webGpu/descriptor/WebGPUDescriptorCreator.ts
Labels: bug

#166 feat(gui): Add api to control visible of gui component
  samples/gui/Sample_UIVisible.ts
  src/components/gui/GUIPick.ts
  src/components/gui/core/GUIGeometry.ts
  src/components/gui/core/GUIQuad.ts
  src/components/gui/core/GUIShader.ts
  src/components/gui/uiComponents/IUIInteractive.ts
  src/components/gui/uiComponents/UIButton.ts
  src/components/gui/uiComponents/UIComponentBase.ts
  src/components/gui/uiComponents/UIImage.ts
  src/components/gui/uiComponents/UIInteractive.ts
  src/components/gui/uiComponents/UIPanel.ts
  src/components/gui/uiComponents/UITextField.ts
  src/components/gui/uiComponents/UITransform.ts
  src/components/gui/uiComponents/ViewPanel.ts
  src/components/gui/uiComponents/WorldPanel.ts
Labels: feature

#172 feat(GUI): Improve GUI
  samples/gui/Sample_UIChangeParent.ts
  src/components/ComponentBase.ts
  src/components/IComponent.ts
  src/components/Transform.ts
  src/components/gui/core/GUIGeometryRebuild.ts
  src/components/gui/uiComponents/UIButton.ts
  src/components/gui/uiComponents/UIComponentBase.ts
  src/components/gui/uiComponents/UIImage.ts
  src/components/gui/uiComponents/UITextField.ts
  src/components/gui/uiComponents/UITransform.ts
Labels: feature

#173 fix(sample): fix propertyAnimation.
  samples/animation/Sample_PropertyAnimation.ts
Labels: bug

#178 fix(blend): samples blended opt
  src/gfx/graphics/webGpu/shader/RenderShader.ts
  src/util/BoundUtil.ts
Labels: bug

#179 fix(Sky): fix AtmosphericSky color
  samples/sky/Sample_AtmosphericSky.ts
  src/assets/shader/sky/AtmosphericScatteringSky_shader.ts
Labels: bug

#174 perf(GUI): performance
  samples/gui/Sample_UIPerformance.ts
  samples/gui/Sample_UIPerformance2.ts
  samples/gui/Sample_UISpriteSheet.ts
  samples/gui/Sample_UITextField.ts
  src/components/gui/core/GUICanvas.ts
  src/components/gui/core/GUIGeometry.ts
  src/components/gui/core/GUIGeometryRebuild.ts
  src/components/gui/core/GUIMaterial.ts
  src/components/gui/core/GUIMesh.ts
  src/components/gui/core/GUIQuad.ts
  src/components/gui/core/GUIRenderer.ts
  src/components/gui/core/GUIShader.ts
  src/components/gui/uiComponents/TextFieldLayout.ts
  src/components/gui/uiComponents/UIComponentBase.ts
  src/components/gui/uiComponents/UIImage.ts
  src/components/gui/uiComponents/UIImageGroup.ts
  src/components/gui/uiComponents/UIPanel.ts
  src/components/gui/uiComponents/UITextField.ts
  src/components/gui/uiComponents/UITransform.ts
  src/components/gui/uiComponents/ViewPanel.ts
  src/components/gui/uiComponents/WorldPanel.ts
  src/core/entities/Object3D.ts
  src/index.ts
Labels: feature

#182 feat(GUI): shadows of GUI
  samples/gui/Sample_UIChangeParent.ts
  samples/gui/Sample_UIImageGroup.ts
  samples/gui/Sample_UIImageShadow.ts
  samples/gui/Sample_UIPerformance2.ts
  samples/gui/Sample_UITextField.ts
  samples/utils/GUIUtil.ts
  src/components/gui/core/GUIDefine.ts
  src/components/gui/core/GUIGeometry.ts
  src/components/gui/core/GUIGeometryRebuild.ts
  src/components/gui/core/GUIQuad.ts
  src/components/gui/uiComponents/UIComponentBase.ts
  src/components/gui/uiComponents/UIImage.ts
  src/components/gui/uiComponents/UIImageGroup.ts
  src/components/gui/uiComponents/UIRenderAble.ts
  src/components/gui/uiComponents/UIShadow.ts
  src/components/gui/uiComponents/UITextField.ts
  src/components/gui/uiComponents/UITransform.ts
  src/index.ts
  src/math/Vector2.ts
Labels: feature

#198 fix(culling): Camera frustum culling
  samples/loader/Sample_LoadGLB.ts
  samples/loader/Sample_LoadGLTF2.ts
  samples/loader/Sample_LoadJson.ts
  src/components/controller/HoverCameraController.ts
  src/core/bound/BoundingBox.ts
  src/core/entities/Entity.ts
  src/gfx/renderJob/passRenderer/graphic/Graphic3DRender.ts
  src/math/Vector3.ts
  src/textures/AtmosphericScatteringSky.ts
  src/util/BoundUtil.ts
  src/util/Object3DUtil.ts
Labels: bug
