Repository Orillusion/orillusion, pull requests merged in 2023-04, with the labels that each got.

#17 feat(math): add math lib
  src/engine/gfx/graphics/webGpu/CanvasConfig.ts
  src/engine/math/AnimationCurve.ts
  src/engine/math/Bezier2D.ts
  src/engine/math/Bezier3D.ts
  src/engine/math/Color.ts
  src/engine/math/Line.ts
  src/engine/math/PolynomialCurve.ts
  src/engine/math/Polynomials.ts
Labels: feature

#16 feat(math): add math lib files
  src/engine/math/HaltonSeq.ts
  src/engine/math/Orientation3D.ts
  src/engine/math/Plane.ts
Labels: feature

#19 feat(memory): add MemoryDO
  src/engine/core/pool/memory/MatrixDO.ts
  src/engine/core/pool/memory/MemoryDO.ts
  src/engine/core/pool/memory/MemoryInfo.ts
Labels: feature

#15 feat(math): add math libs
  src/engine/math/Rand.ts
  src/engine/math/Random.ts
  src/engine/math/Ray.ts
  src/engine/math/Rect.ts
  src/engine/math/TimeInterpolator.ts
  src/engine/math/Triangle.ts
  src/engine/math/UV.ts
  src/engine/math/Vector2.ts
  src/engine/math/Vector3.ts
  src/engine/math/Vector4.ts
Labels: feature

#13 feat(math): base math
  src/engine/math/Matrix3.ts
  src/engine/math/Matrix4.ts
  src/engine/math/Quaternion.ts
Labels: feature

#21 feat(event): add event lib
  src/engine/event/CEvent.ts
  src/engine/event/CEventDispatcher.ts
  src/engine/event/CEventListener.ts
  src/engine/event/CResizeEvent.ts
  src/engine/event/KeyCode.ts
  src/engine/event/MouseCode.ts
Labels: feature

#18 feat(WebGPU): Add WebGPU Context
  src/engine/gfx/generate/BrdfLUTGenerate.ts
  src/engine/gfx/generate/PassGenerate.ts
  src/engine/gfx/generate/convert/IBLEnvMapCreator.ts
  src/engine/gfx/generate/convert/MergeRGBACreator.ts
  src/engine/gfx/generate/graphic/webgpu/Context3D.ts
  src/engine/gfx/generate/graphic/webgpu/WebGPUConst.ts
  src/engine/gfx/generate/graphic/webgpu/core/bindGroups/GlobalBindGroup.ts
  src/engine/gfx/generate/graphic/webgpu/core/bindGroups/GlobalBindGroupLayout.ts
  src/engine/gfx/generate/graphic/webgpu/core/bindGroups/GlobalUniformGroup.ts
  src/engine/gfx/generate/graphic/webgpu/core/bindGroups/MatrixBindGroup.ts
  src/engine/gfx/generate/graphic/webgpu/core/bindGroups/TexturesBindGroup.ts
  src/engine/gfx/generate/graphic/webgpu/core/bindGroups/groups/LightEntries.ts
  src/engine/gfx/generate/graphic/webgpu/core/bindGroups/groups/ProbeEntries.ts
  src/engine/gfx/generate/renderJob/GPUContext.ts
  src/engine/math/Matrix4.ts
Labels: feature

#28 feat(ecs): add base entity
  .gitignore
  src/engine/Engine3D.ts
  src/engine/assets/Res.ts
  src/engine/core/entities/Entity.ts
  src/engine/core/entities/Object3D.ts
  src/engine/gfx/generate/graphic/webgpu/core/bindGroups/GlobalUniformGroup.ts
  src/engine/math/Color.ts
  src/engine/math/Line.ts
  src/engine/math/MathUtil.ts
  src/engine/math/Matrix4.ts
Labels: feature

#36 chore(bindgroup): change folder
  src/engine/gfx/graphics/webGpu/Context3D.ts
  src/engine/gfx/graphics/webGpu/WebGPUConst.ts
  src/engine/gfx/graphics/webGpu/core/bindGroups/GlobalBindGroup.ts
  src/engine/gfx/graphics/webGpu/core/bindGroups/GlobalBindGroupLayout.ts
  src/engine/gfx/graphics/webGpu/core/bindGroups/GlobalUniformGroup.ts
  src/engine/gfx/graphics/webGpu/core/bindGroups/MatrixBindGroup.ts
  src/engine/gfx/graphics/webGpu/core/bindGroups/TexturesBindGroup.ts
  src/engine/gfx/graphics/webGpu/core/bindGroups/groups/LightEntries.ts
  src/engine/gfx/graphics/webGpu/core/bindGroups/groups/ProbeEntries.ts
  src/engine/gfx/renderJob/GPUContext.ts
Labels: feature

#40 feat(GPUBuffer): add GPUBuffer wrapper
  src/engine/gfx/graphics/webGpu/core/buffer/ComputeGPUBuffer.ts
  src/engine/gfx/graphics/webGpu/core/buffer/GPUBufferBase.ts
  src/engine/gfx/graphics/webGpu/core/buffer/IndicesGPUBuffer.ts
  src/engine/gfx/graphics/webGpu/core/buffer/VertexGPUBuffer.ts
Labels: feature

#39 feat(memory): add UniformNode
  src/engine/gfx/graphics/webGpu/core/uniforms/UniformNode.ts
Labels: feature

#45 feat(webGPU): add create WebGPU texture cube code.
  src/engine/gfx/generate/convert/BlurEffectCreator.ts
  src/engine/gfx/generate/convert/ErpImage2CubeMap.ts
  src/engine/gfx/generate/convert/TextureCubeStdCreator.ts
  src/engine/gfx/generate/convert/TextureCubeUtils.ts
Labels: feature

#24 feat(shader): add shader module and resource
  src/engine/assets/shader/ShaderLib.ts
  src/engine/assets/shader/core/pass/CastShadowPass_wgsl.ts
  src/engine/assets/shader/core/pass/FrustumCullingShader_cs.wgsl
  src/engine/assets/shader/core/pass/GBuffer_shader.wgsl
  src/engine/assets/shader/core/pass/SkyGBuffer_fs.wgsl
  src/engine/assets/shader/core/pass/ZPassShader_cs.wgsl
  src/engine/assets/shader/core/pass/ZPassShader_fs.wgsl
  src/engine/assets/shader/core/pass/ZPassShader_vs.ts
  src/engine/assets/shader/core/struct/ColorPassFragmentOutput.wgsl
  src/engine/assets/shader/core/struct/EmptyFrag_CommonFragment.wgsl
  src/engine/assets/shader/core/struct/EmptyFrag_FragmentOutput.wgsl
  src/engine/assets/shader/core/struct/FragmentVarying.wgsl
  src/engine/assets/shader/core/struct/LightStruct.wgsl
  src/engine/assets/shader/core/struct/LightStructFrag.ts
  src/engine/assets/shader/core/struct/ShadingInput.wgsl
  src/engine/assets/shader/core/struct/VertexAttributes.ts
  src/engine/assets/shader/glsl/Quad_glsl.ts
  src/engine/assets/shader/glsl/Sky_glsl.ts
  src/engine/assets/shader/glsl/post/LUT_glsl.ts
  src/engine/assets/shader/lighting/BRDF_frag.wgsl
  src/engine/assets/shader/lighting/BxDF_frag.wgsl
  src/engine/assets/shader/lighting/IESProfiles_frag.wgsl
  src/engine/assets/shader/lighting/Irradiance_frag.wgsl
  src/engine/assets/shader/lighting/LightingFunction_frag.ts
  src/engine/assets/shader/lighting/UnLit_frag.ts
  src/engine/assets/shader/materials/ColorLitShader.ts
  src/engine/assets/shader/materials/PavementShader.ts
  src/engine/assets/shader/materials/PointShadowDebug.ts
  src/engine/assets/shader/materials/program/BxdfDebug_frag.wgsl
  src/engine/assets/shader/materials/program/Clearcoat_frag.wgsl
  src/engine/assets/shader/materials/program/ClusterDebug_frag.ts
  src/engine/assets/shader/materials/program/NormalMap_frag.wgsl
  src/engine/assets/shader/materials/program/ShadowMapping_frag.wgsl
  src/engine/assets/shader/materials/uniforms/MaterialUniform.ts
  src/engine/assets/shader/materials/uniforms/PhysicMaterialUniform_frag.ts
  src/engine/assets/shader/materials/uniforms/UnLitMaterialUniform_frag.ts
  src/engine/assets/shader/materials/uniforms/VideoUniform_frag.ts
  src/engine/gfx/graphics/webGpu/shader/value/ConstValue.ts
  src/engine/gfx/graphics/webGpu/shader/value/DefineValue.ts
  src/engine/gfx/graphics/webGpu/shader/value/ShaderReflectionInfo.ts
  src/engine/gfx/graphics/webGpu/shader/value/ShaderState.ts
  src/engine/gfx/graphics/webGpu/shader/value/ShaderValue.ts
  src/engine/gfx/graphics/webGpu/shader/value/UniformValue.ts
Labels: feature

#38 feat(shader): add shader module
  src/engine/assets/shader/anim/SkeletonAnimation_shader.ts
  src/engine/assets/shader/compute/BlurEffectCreator_compute.ts
  src/engine/gfx/graphics/webGpu/shader/ShaderStage.ts
  src/engine/gfx/graphics/webGpu/shader/converter/GLSLLexer.ts
  src/engine/gfx/graphics/webGpu/shader/converter/GLSLLexerToken.ts
  src/engine/gfx/graphics/webGpu/shader/converter/GLSLPreprocessor.ts
  src/engine/gfx/graphics/webGpu/shader/converter/GLSLSyntax.ts
  src/engine/gfx/graphics/webGpu/shader/converter/Reader.ts
  src/engine/gfx/graphics/webGpu/shader/converter/ShaderConverter.ts
  src/engine/gfx/graphics/webGpu/shader/converter/StatementNode.ts
  src/engine/gfx/graphics/webGpu/shader/converter/WGSLTranslator.ts
  src/engine/gfx/graphics/webGpu/shader/util/MorePassParser.ts
  src/engine/gfx/graphics/webGpu/shader/util/Preprocessor.ts
  src/engine/gfx/graphics/webGpu/shader/util/ShaderUtil.ts
Labels: feature

#41 feat(io): Add io files
  src/engine/io/InputSystem.ts
  src/engine/io/PickFire.ts
  src/engine/io/PickResult.ts
  src/engine/io/RayCastMeshDetail.ts
  src/engine/io/TouchData.ts
  src/engine/io/picker/PickCompute.ts
Labels: feature

#47 feat(component): Add collider components and kdtree into engine.
  src/engine/components/ColliderComponent.ts
  src/engine/components/shape/BoxColliderShape.ts
  src/engine/components/shape/CapsuleColliderShape.ts
  src/engine/components/shape/ColliderShape.ts
  src/engine/components/shape/MeshColliderShape.ts
  src/engine/components/shape/SphereColliderShape.ts
  src/engine/core/pool/ObjectPool.ts
  src/engine/core/tree/kdTree/IKDTreeUserData.ts
  src/engine/core/tree/kdTree/KDTreeEntity.ts
  src/engine/core/tree/kdTree/KDTreeNode.ts
  src/engine/core/tree/kdTree/KDTreeSpace.ts
Labels: feature

#32 feat(loaderAndParser): Add loader and parser files
  src/engine/loader/FileLoader.ts
  src/engine/loader/LoaderBase.ts
  src/engine/loader/LoaderData.ts
  src/engine/loader/LoaderFunctions.ts
  src/engine/loader/LoaderManager.ts
  src/engine/loader/parser/AtlasParser.ts
  src/engine/loader/parser/B3DMParser.ts
  src/engine/loader/parser/FntParser.ts
  src/engine/loader/parser/I3DMParser.ts
  src/engine/loader/parser/OBJParser.ts
  src/engine/loader/parser/ParserBase.ts
  src/engine/loader/parser/RGBEParser.ts
  src/engine/loader/parser/b3dm/B3DMLoader.ts
  src/engine/loader/parser/b3dm/B3DMLoaderBase.ts
  src/engine/loader/parser/b3dm/FeatureTable.ts
  src/engine/loader/parser/b3dm/arrayToString.ts
  src/engine/loader/parser/b3dm/readMagicBytes.ts
  src/engine/loader/parser/i3dm/I3DMLoader.ts
  src/engine/loader/parser/i3dm/I3DMLoaderBase.ts
  src/engine/loader/parser/tileRenderer/TileSet.ts
  src/engine/loader/parser/tileRenderer/TilesRenderer.ts
Labels: feature

#52 feat(memory-struct): add struct
  src/engine/util/struct/Struct.ts
  src/engine/util/struct/StructValue.ts
  src/engine/util/struct/Vector3Struct.ts
Labels: feature

#49 feat(util): add util files
  src/engine/util/AxisObject.ts
  src/engine/util/BytesStream.ts
  src/engine/util/CameraUtil.ts
  src/engine/util/Convert.ts
  src/engine/util/GeometryUtil.ts
  src/engine/util/Global.ts
  src/engine/util/KelvinUtil.ts
  src/engine/util/Object3DUtil.ts
  src/engine/util/ProfilerUtil.ts
  src/engine/util/StringUtil.ts
  src/engine/util/Time.ts
  src/engine/util/Vector3Ex.ts
  src/engine/util/ZSorterUtil.ts
Labels: feature

#51 feat(parser): add gltf parser
  src/engine/loader/parser/gltf/GLBParser.ts
  src/engine/loader/parser/gltf/GLTFInfo.ts
  src/engine/loader/parser/gltf/GLTFParser.ts
  src/engine/loader/parser/gltf/GLTFSubParser.ts
  src/engine/loader/parser/gltf/GLTFSubParserCamera.ts
  src/engine/loader/parser/gltf/GLTFSubParserConverter.ts
  src/engine/loader/parser/gltf/GLTFSubParserMaterial.ts
  src/engine/loader/parser/gltf/GLTFSubParserMesh.ts
  src/engine/loader/parser/gltf/GLTFSubParserSkeleton.ts
  src/engine/loader/parser/gltf/GLTFSubParserSkin.ts
  src/engine/loader/parser/gltf/TypeArray.ts
  src/engine/loader/parser/gltf/extends/KHR_draco_mesh_compression.ts
  src/engine/loader/parser/gltf/extends/KHR_lights_punctual.ts
  src/engine/loader/parser/gltf/extends/KHR_materials_clearcoat.ts
  src/engine/loader/parser/gltf/extends/KHR_materials_emissive_strength.ts
  src/engine/loader/parser/gltf/extends/KHR_materials_ior.ts
  src/engine/loader/parser/gltf/extends/KHR_materials_sheen.ts
  src/engine/loader/parser/gltf/extends/KHR_materials_specular.ts
  src/engine/loader/parser/gltf/extends/KHR_materials_transmission.ts
  src/engine/loader/parser/gltf/extends/KHR_materials_unlit.ts
  src/engine/loader/parser/gltf/extends/KHR_materials_variants.ts
  src/engine/loader/parser/gltf/extends/KHR_materials_volume.ts
  src/engine/loader/parser/gltf/extends/KHR_mesh_quantization.ts
  src/engine/loader/parser/gltf/extends/KHR_texture_basisu.ts
  src/engine/loader/parser/gltf/extends/KHR_texture_transform.ts
Labels: feature

#33 feat(morph): Add morph files
  src/engine/components/anim/OAnimationEvent.ts
  src/engine/components/anim/morphAnim/MorphTargetBlender.ts
  src/engine/components/anim/morphAnim/MorphTargetData.ts
  src/engine/components/anim/morphAnim/MorphTargetFrame.ts
  src/engine/components/anim/morphAnim/MorphTargetKey.ts
  src/engine/components/anim/morphAnim/MorphTarget_shader.ts
Labels: feature

#54 feat(GPUBuffer): add GPU Buffer
  src/engine/core/geometry/GeometryBase.ts
  src/engine/core/geometry/GeometryIndicesBuffer.ts
  src/engine/core/geometry/GeometryVertexBuffer.ts
  src/engine/core/geometry/GeometryVertexType.ts
  src/engine/core/geometry/VertexAttribute.ts
  src/engine/core/geometry/VertexAttributeData.ts
  src/engine/core/geometry/VertexAttributeName.ts
  src/engine/core/geometry/VertexAttributeSize.ts
  src/engine/core/geometry/VertexAttributeStride.ts
  src/engine/core/geometry/VertexFormat.ts
  src/engine/gfx/graphics/webGpu/core/buffer/MaterialDataUniformGPUBuffer.ts
  src/engine/gfx/graphics/webGpu/core/buffer/StorageGPUBuffer.ts
  src/engine/gfx/graphics/webGpu/core/buffer/StructStorageGPUBuffer.ts
  src/engine/gfx/graphics/webGpu/core/buffer/UniformGPUBuffer.ts
Labels: feature

#42 feat(Graphic3D): add wireframe graphics to draw
  src/engine/gfx/renderJob/passRenderer/graphic/Graphic3DBatchRenderer.ts
  src/engine/gfx/renderJob/passRenderer/graphic/Graphic3DFillRenderer.ts
  src/engine/gfx/renderJob/passRenderer/graphic/Graphic3DFixedRenderPipeline.ts
  src/engine/gfx/renderJob/passRenderer/graphic/Graphic3DLineBatchRenderer.ts
  src/engine/gfx/renderJob/passRenderer/graphic/Graphic3DRender.ts
  src/engine/gfx/renderJob/passRenderer/graphic/GraphicConfig.ts
  src/engine/gfx/renderJob/passRenderer/graphic/Graphics3DShape.ts
Labels: feature

#59 feat(audio): add audio components
  src/engine/components/audio/AudioListener.ts
  src/engine/components/audio/PositionAudio.ts
  src/engine/components/audio/StaticAudio.ts
Labels: feature

#55 feat(SkeletonAnimation): add skeleton animation component
  src/engine/components/SkeletonAnimationComponent.ts
  src/engine/components/anim/skeletonAnim/Joint.ts
  src/engine/components/anim/skeletonAnim/JointPose.ts
  src/engine/components/anim/skeletonAnim/Skeleton.ts
  src/engine/components/anim/skeletonAnim/SkeletonAnimationClip.ts
  src/engine/components/anim/skeletonAnim/SkeletonAnimationClipState.ts
  src/engine/components/anim/skeletonAnim/SkeletonAnimationCompute.ts
  src/engine/components/anim/skeletonAnim/SkeletonPose.ts
  src/engine/components/anim/skeletonAnim/buffer/SkeletonBlendComputeArgs.ts
  src/engine/components/anim/skeletonAnim/buffer/SkeletonTransformComputeArgs.ts
  src/engine/components/anim/skeletonAnim/shader/compute_skeleton_blend.ts
  src/engine/components/anim/skeletonAnim/shader/compute_skeleton_transform.ts
Labels: feature

#58 feat(Camera): add camera controller
  src/engine/components/controller/CameraControllerBase.ts
  src/engine/components/controller/FirstPersonCameraController.ts
  src/engine/components/controller/FlyCameraController.ts
  src/engine/components/controller/HoverCameraController.ts
  src/engine/components/controller/ThirdPersonCameraController.ts
Labels: feature

#57 feat(render): add render framework
  src/engine/gfx/graphics/webGpu/core/Camera3D.ts
  src/engine/gfx/graphics/webGpu/core/CameraType.ts
  src/engine/gfx/graphics/webGpu/core/CubeCamera.ts
  src/engine/gfx/graphics/webGpu/core/PointShadowCubeCamera.ts
  src/engine/gfx/graphics/webGpu/core/ViewQuad.ts
  src/engine/gfx/renderJob/collect/CollectInfo.ts
  src/engine/gfx/renderJob/collect/EntityBatchCollect.ts
  src/engine/gfx/renderJob/collect/EntityCollect.ts
  src/engine/gfx/renderJob/collect/RenderGroup.ts
  src/engine/gfx/renderJob/collect/ShadowLightsCollect.ts
  src/engine/gfx/renderJob/color/ColorPassRenderer.ts
  src/engine/gfx/renderJob/config/RTResourceConfig.ts
  src/engine/gfx/renderJob/config/RenderLayer.ts
  src/engine/gfx/renderJob/frame/GBufferFrame.ts
  src/engine/gfx/renderJob/frame/ProbeGBufferFrame.ts
  src/engine/gfx/renderJob/frame/RTFrame.ts
  src/engine/gfx/renderJob/frame/RTResourceMap.ts
  src/engine/gfx/renderJob/jobs/ForwardRenderJob.ts
  src/engine/gfx/renderJob/jobs/RenderMap.ts
  src/engine/gfx/renderJob/jobs/RendererJob.ts
  src/engine/gfx/renderJob/occlusion/OcclusionSystem.ts
  src/engine/gfx/renderJob/passRenderer/RenderContext.ts
  src/engine/gfx/renderJob/passRenderer/RendererBase.ts
  src/engine/gfx/renderJob/preDepth/PreDepthPassRenderer.ts
  src/engine/gfx/renderJob/preDepth/ZCullingCompute.ts
  src/engine/gfx/renderJob/state/RendererMask.ts
  src/engine/gfx/renderJob/state/RendererPassState.ts
  src/engine/gfx/renderJob/state/RendererType.ts
  src/engine/setting/EngineSetting.ts
Labels: feature

#61 feat(bound): add bound
  src/engine/gfx/graphics/webGpu/core/Camera3D.ts
  src/engine/gfx/graphics/webGpu/core/bound/BoundingBox.ts
  src/engine/gfx/graphics/webGpu/core/bound/BoundingSphere.ts
  src/engine/gfx/graphics/webGpu/core/bound/Frustum.ts
  src/engine/gfx/graphics/webGpu/core/bound/IBound.ts
Labels: feature

#62 feat(camera): add orbit camera controller
  src/engine/components/controller/OrbitController.ts
Labels: feature

#63 feat(material): add materials
  src/engine/materials/BlendMode.ts
  src/engine/materials/ColorLitMaterial.ts
  src/engine/materials/GIProbeMaterial.ts
  src/engine/materials/GlassMaterial.ts
  src/engine/materials/LambertMaterial.ts
  src/engine/materials/LitMaterial.ts
  src/engine/materials/MaterialBase.ts
  src/engine/materials/MaterialPass.ts
  src/engine/materials/multiPass/CastPointShadowMaterialPass.ts
  src/engine/materials/multiPass/CastShadowMaterialPass.ts
  src/engine/materials/multiPass/DepthMaterialPass.ts
  src/engine/materials/multiPass/GBufferPass.ts
  src/engine/materials/multiPass/SkyGBufferPass.ts
Labels: feature

#66 feat(ECS): Add ECS files
  src/engine/components/AtmosphericComponent.ts
  src/engine/components/BillboardComponent.ts
  src/engine/components/ComponentBase.ts
  src/engine/components/Transform.ts
  src/engine/components/post/PostProcessingComponent.ts
  src/engine/components/renderer/GlobalIlluminationComponent.ts
  src/engine/components/renderer/InstanceDrawComponent.ts
  src/engine/components/renderer/MaterialComponent.ts
  src/engine/components/renderer/MeshComponent.ts
  src/engine/components/renderer/MeshRenderer.ts
  src/engine/components/renderer/RenderNode.ts
  src/engine/components/renderer/SkinnedMeshRenderer.ts
  src/engine/components/renderer/SkyRenderer.ts
Labels: feature

#64 feat(light): add cluster lighting
  src/engine/components/lights/DirectLight.ts
  src/engine/components/lights/GILighting.ts
  src/engine/components/lights/IESProfiles.ts
  src/engine/components/lights/LightBase.ts
  src/engine/components/lights/LightData.ts
  src/engine/components/lights/PointLight.ts
  src/engine/components/lights/SpotLight.ts
  src/engine/gfx/renderJob/passRenderer/cluster/ClusterLightingRender.ts
Labels: feature

#68 feat(materials): add materials
  src/engine/materials/MaterialRegister.ts
  src/engine/materials/PavementMaterial.ts
  src/engine/materials/PhysicMaterial.ts
  src/engine/materials/PointMaterial.ts
  src/engine/materials/SkyMaterial.ts
  src/engine/materials/UnLitMaterial.ts
  src/engine/materials/effectPass/OutLinePass.ts
Labels: feature

#69 feat(shape): add shape
  src/engine/shape/BoxGeometry.ts
  src/engine/shape/CylinderGeometry.ts
  src/engine/shape/PlaneGeometry.ts
  src/engine/shape/SphereGeometry.ts
  src/engine/shape/TorusGeometry.ts
Labels: feature

#71 chore: folder error
  src/engine/components/ComponentBase.ts
  src/engine/core/Camera3D.ts
  src/engine/core/CameraType.ts
  src/engine/core/CubeCamera.ts
  src/engine/core/PointShadowCubeCamera.ts
  src/engine/core/Scene3D.ts
  src/engine/core/View3D.ts
  src/engine/core/ViewQuad.ts
  src/engine/core/bound/BoundingBox.ts
  src/engine/core/bound/BoundingSphere.ts
  src/engine/core/bound/Frustum.ts
  src/engine/core/bound/IBound.ts
  src/engine/math/Matrix4.ts
Labels: bug

#74 Dev
  src/engine/gfx/graphics/webGpu/descriptor/RTDescriptor.ts
  src/engine/gfx/graphics/webGpu/descriptor/WebGPUDescriptorCreator.ts
  src/engine/gfx/graphics/webGpu/shader/ComputeShader.ts
  src/engine/gfx/graphics/webGpu/shader/RenderShader.ts
  src/engine/gfx/graphics/webGpu/shader/ShaderBase.ts
Labels: feature

#75 feat(Mesh): add InstanceMesh
  src/engine/core/entities/InstancedMesh.ts
Labels: feature

#77 feat(clusterLighting): add cluster lighting shader
  src/engine/assets/shader/cluster/ClusterBoundsSource_cs.wgsl
  src/engine/assets/shader/cluster/ClusterLighting_cs.wgsl
Labels: feature

#78 docs: update docs
  src/engine/assets/Res.ts
  src/engine/io/InputSystem.ts
  src/engine/loader/parser/gltf/GLBParser.ts
  src/engine/loader/parser/gltf/GLTFInfo.ts
  src/engine/loader/parser/gltf/GLTFParser.ts
  src/engine/loader/parser/gltf/GLTFSubParser.ts
  src/engine/loader/parser/gltf/GLTFSubParserMesh.ts
Labels: feature

#79 feat(ComputeShader): add cs shader
  src/engine/assets/shader/ShaderLib.ts
  src/engine/assets/shader/compute/BLUR_CsShader.wgsl
  src/engine/assets/shader/compute/DepthOfView_CsShader.wgsl
  src/engine/assets/shader/compute/ErpImage2CubeMapCreateCube_compute.wgsl
  src/engine/assets/shader/compute/ErpImage2CubeMapRgbe2rgba_compute.wgsl
  src/engine/assets/shader/compute/GTAOCs.wgsl
  src/engine/assets/shader/compute/IBLEnvMapCreator_compute.wgsl
  src/engine/assets/shader/compute/MergeRGBA_Cs.wgsl
  src/engine/assets/shader/compute/MultiBouncePass_Shader.wgsl
  src/engine/assets/shader/compute/OutLineBlendColor.wgsl
  src/engine/assets/shader/compute/OutlineCalcOutline.wgsl
  src/engine/assets/shader/compute/OutlineCs.wgsl
  src/engine/assets/shader/compute/Picker_CsShader.wgsl
  src/engine/assets/shader/compute/SSAO_CsShader.wgsl
  src/engine/assets/shader/compute/SSR_BlendColor_Shader.wgsl
  src/engine/assets/shader/compute/SSR_IS_Shader.wgsl
  src/engine/assets/shader/compute/SSR_RayTrace_Shader.wgsl
  src/engine/assets/shader/compute/TAACopyTex.wgsl
  src/engine/assets/shader/compute/TAASharpTex.wgsl
  src/engine/assets/shader/compute/TAAcs.wgsl
  src/engine/assets/shader/core/base/Common_frag.wgsl
  src/engine/assets/shader/core/base/Common_vert.wgsl
  src/engine/assets/shader/core/common/BrdfLut_frag.wgsl
  src/engine/assets/shader/core/common/EnvMap_frag.wgsl
  src/engine/assets/shader/core/common/GlobalUniform.wgsl
  src/engine/assets/shader/core/common/InstanceUniform.wgsl
  src/engine/assets/shader/core/common/WorldMatrixUniform.wgsl
  src/engine/assets/shader/core/inline/Inline_vert.wgsl
  src/engine/assets/shader/graphic/Graphic3DShader_fs.wgsl
  src/engine/assets/shader/graphic/Graphic3DShader_vs.wgsl
  src/engine/assets/shader/materials/GlassShader.wgsl
  src/engine/assets/shader/materials/LitShader.wgsl
  src/engine/assets/shader/materials/OutlinePass.wgsl
  src/engine/assets/shader/materials/PBRLItShader.wgsl
  src/engine/assets/shader/materials/UnLit.wgsl
  src/engine/assets/shader/materials/sky/AtmosphericScatteringSky_shader.ts
  src/engine/assets/shader/materials/sky/CubeSky_Shader.ts
  src/engine/assets/shader/math/FastMathShader.wgsl
  src/engine/assets/shader/post/FSAAShader.wgsl
  src/engine/assets/shader/utils/BRDFLUT.wgsl
  src/engine/assets/shader/utils/ColorUtil.wgsl
  src/engine/assets/shader/utils/GenerayRandomDir.wgsl
  src/engine/textures/AtmosphericScatteringSky.ts
Labels: feature

#80 docs: add CI & NPM badges
  .github/workflows/ci.yml
  README.md
Labels: documentation
