Repository Orillusion/orillusion, pull requests merged in 2023-07, with the labels that each got.

#250 feat(globalFog): add feature of height fog
  samples/post/Sample_Fog.ts
  samples/utils/GUIUtil.ts
  src/Engine3D.ts
  src/assets/shader/post/GlobalFog_shader.ts
  src/gfx/renderJob/post/GlobalFog.ts
  src/setting/post/GlobalFogSetting.ts
Labels: feature

#243 chore(Vector3): remove cross method
  src/Engine3D.ts
  src/io/RayCastMeshDetail.ts
  src/loader/parser/i3dm/I3DMLoader.ts
  src/math/MathUtil.ts
  src/math/Matrix4.ts
  src/math/Ray.ts
  src/math/Triangle.ts
  src/math/Vector3.ts
Labels: feature

#254 fix(AtmosphericScattering): Fix sky Rendering error in the MAC environment.
  src/assets/shader/compute/ErpImage2CubeMapCreateCube_cs.ts
Labels: bug

#257 perf(BoundingBox): add isBoundChange tag to Entity
  samples/base/Sample_BoundingBox.ts
  src/components/ComponentBase.ts
  src/components/Transform.ts
  src/core/bound/Frustum.ts
  src/core/entities/Entity.ts
  src/core/entities/Object3D.ts
Labels: feature

#255 fix(engine): Fixed a series of issues and improved functionality
  samples/pick/Sample_MeshColliderPick.ts
  src/Engine3D.ts
  src/components/ColliderComponent.ts
  src/components/ComponentBase.ts
  src/components/anim/curveAnim/AnimationMonitor.ts
  src/components/anim/curveAnim/PropertyAnimation.ts
  src/components/anim/curveAnim/PropertyHelp.ts
  src/components/gui/GUIConfig.ts
  src/components/gui/GUIPick.ts
  src/components/gui/GUIPickHelper.ts
  src/components/gui/core/GUICanvas.ts
  src/components/gui/core/GUIGeometry.ts
  src/components/gui/core/GUIGeometryRebuild.ts
  src/components/gui/core/GUIMaterial.ts
  src/components/gui/core/GUIQuad.ts
  src/components/gui/core/GUIShader.ts
  src/components/gui/uiComponents/UIInteractive.ts
  src/components/gui/uiComponents/UIPanel.ts
  src/components/gui/uiComponents/UITextField.ts
  src/components/renderer/MeshRenderer.ts
  src/components/renderer/RenderNode.ts
  src/components/shape/BoxColliderShape.ts
  src/components/shape/ColliderShape.ts
  src/components/shape/MeshColliderShape.ts
  src/components/shape/SphereColliderShape.ts
  src/core/entities/Object3D.ts
  src/core/pool/ObjectPool.ts
  src/gfx/graphics/webGpu/core/uniforms/UniformNode.ts
  src/index.ts
  src/io/PickFire.ts
  src/materials/LitMaterial.ts
  src/materials/MaterialBase.ts
  src/materials/UnLitMaterial.ts
  src/math/Vector3.ts
  src/util/SerializeDecoration.ts
  test/components/ECS.test.ts
Labels: bug

#264 chore: chore uuid
  packages/debug/GUIHelp.ts
  samples/base/Sample_BoundingBox.ts
  samples/benchmark/Sample_SphereDraw.ts
  samples/benchmark/Sample_drawCall.ts
  samples/material/Sample_RenderPassClean.ts
  src/Engine3D.ts
  src/components/Transform.ts
  src/components/lights/PointLight.ts
  src/components/lights/SpotLight.ts
  src/components/renderer/RenderNode.ts
  src/core/entities/Entity.ts
  src/core/geometry/GeometryBase.ts
  src/gfx/renderJob/passRenderer/graphic/Graphic3DRender.ts
  src/io/PickFire.ts
  src/math/Matrix4.ts
  src/util/Global.ts
  test/math/MatrixDO.test.ts
Labels: bug, feature

#265 feat: graphic
  samples/graphic/Sample_GraphicLine.ts
  src/gfx/graphics/webGpu/core/uniforms/UniformNode.ts
Labels: feature

#268 fix: fix material uniformNode not update
  samples/material/Sample_UVMove.ts
  src/assets/shader/lighting/BxDF_frag.ts
  src/gfx/graphics/webGpu/core/uniforms/UniformNode.ts
  src/io/PickFire.ts
Labels: bug
